# Generated by Django 3.2.9 on 2021-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
